sudo: false
language: python
jdk: oraclejdk7
services:
  - mysql
  - postgresql
python: 
  - "2.7"
env:
  - TOX_ENV=py27-cdh
  - TOX_ENV=py27-hdp
install:
  - pip install tox
before_script:
  - mysql -e 'create database airflow'
  - psql -c 'create database airflow;' -U postgres
script:
  - tox --version
  - travis_wait ./run_tox.sh
