sudo: false
language: python
jdk: oraclejdk7
services:
  - mysql
  - postgresql
python: 
  - "2.7"
env:
  - TOX_ENV=py27-cdh
  - TOX_ENV=py27-hdp
cache:
  directories:
    - $HOME/.wheelhouse/
install:
  - pip install --upgrade pip
  - pip install tox
before_script:
  - mysql -e 'create database airflow'
  - psql -c 'create database airflow;' -U postgres
script:
  - pip --version
  - ls -l $HOME/.wheelhouse
  - tox --version
  - tox -e $TOX_ENV

