sudo: false
language: python
jdk: oraclejdk7
python: 
  - "2.7"
env:
  - TOX_ENV=py27-cdh
  - TOX_ENV=py27-hdp
install:
  - pip install tox
script:
  - tox --version
  - travis_wait 30 python setup.py test --tox-args="-v -e $TOX_ENV"
