sudo: false
language: python
jdk: oraclejdk7
services:
  - mysql
  - postgresql
python: 
  - "2.7"
env:
  - TOX_ENV=py27-cdh PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOX_ENV=py27-hdp PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/.wheelhouse/
install:
  - pip install --upgrade pip
  - pip install tox
before_script:
  - mysql -e 'create database airflow'
  - psql -c 'create database airflow;' -U postgres
script:
  - pip --version
  - pip wheel --wheel-dir=$HOME/.wheelhouse -r requirements.txt
  - tox --version
  - ./run_tox.sh

